site_name: MagusTerra

theme:
  name: material
  icon:
    logo: material/book-open-page-variant

  palette: 
    # Palette toggle for light mode
    - scheme: ancient
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - MagusTerra: index.md
  - Zones:
    - Howling Timber:
        - Howling Timber: zones/howlingTimber/howlingTimber.md
        - The SilverMoon Trackers: zones/howlingTimber/silverMoonTrackers.md
        - Vehkmoss: zones/howlingTimber/vehkmoss.md
  - Races of MagusTerra: 
    - Vehkran:
      - Vehkran: races/vehkran.md
      - Sangvehk: races/sangvehk.md
    - Efos:  races/efos.md
    - Halflings: races/halflings.md
  - Cosmos:
    - Dull Moon: cosmos/dullMoon.md
    - Vibrant Moon: cosmos/vibrantMoon.md

extra_css:
  - stylesheets/extra.css