site_name: MagusTerra

theme:
  name: material

nav:
  - MagusTerra: index.md
  - Zones:
    - Howling Timber: 
      - The SilverMoon Trackers: zones/howlingTimber/silverMoonTrackers.md
      - Vehkmoss: zones/howlingTimber/vehkmoss.md
  - Races of MagusTerra: 
    - Vehkran:
      - Vehkran: races/vehkran.md
      - Sangvehk: races/sangvehk.md
    - Efos:  races/efos.md
    - Halflings: races/halflings.md


extra_css:
  - stylesheets/extra.css