site_name: MagusTerra

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: ancient
      primary: pink
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - MagusTerra: index.md
  - Zones:
    - Howling Timber: 
      - The SilverMoon Trackers: zones/howlingTimber/silverMoonTrackers.md
      - Vehkmoss: zones/howlingTimber/vehkmoss.md
  - Races of MagusTerra: 
    - Vehkran:
      - Vehkran: races/vehkran.md
      - Sangvehk: races/sangvehk.md
    - Efos:  races/efos.md
    - Halflings: races/halflings.md


extra_css:
  - stylesheets/extra.css